# Change these first
owner: linbuxiao # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: TwitterSearch
    url: http://8.134.220.225:16100/profile?user_id=169686021&tweet_type=Tweets
    headers: 
      - "Authorization: $X_TOKEN"
      
status-website:
  baseUrl: /uptime # "repo" is your repository name
